### ISSUE TITLE
Mod refuses to launch or install

### ISSUE THREAD

**Issue by KingVoyd** [BubkisLord/Fyrenest#10]
Upon first install, I could launch the mod but it would "fail to call constructor". I unenabled it but then it didn't like when I reenabled (the button turns grey and I can no longer interact with Scarab). I uninstalled it, and have since tried to reinstall, but it won't work. Scarab just won't stop loading when I hit install now. I can close Scarab and reopen it without problem to use it again, but Fyrenest will remain the same in that interacting with it causes problems.

**Comment by BubkisLord** [comment]
Try using Scarab+ or manually uninstall the mod properly. When loading the mod, make sure you have the correct version of the mod with all the dependencies installed.
