### ISSUE TITLE
Benchwarp issue

### ISSUE THREAD

**Issue by RoninRulez** [BubkisLord/Fyrenest#19]
Fyrenest doesn't work with Benchwarp for some reason. You cant warp. The menu is still there, but you can't warp.

**Comment by BubkisLord** [comment]
This issue's never been reported before and my mod's been out for a long time.

I've always used benchwarp and it's worked with Fyrenest for me. Could you give me the full modlist that you're using? It's possible that there's some other mod that is messing with benchwarp. (Maybe you are missing some dependencies for something)

Currently you haven't really given much information and I don't see how this issue could have arisen.

Thanks.

**Comment by RoninRulez** [comment]
Additional Maps, Benchwarp, BenchWarpFix, Bomber Knight, Charm Changer, Charm Overhual, Curse Randomizer, Custom Knight, CustomKnightPlus, DamageValues, DebugMod, Enemy HP Bar, FrogCore, HKMirror, InfiniteNotches, Item Changer, Korz Utils, Magic UI, Menu Changer, ModTerminal, Pale Court, QoL, Randomizer 4, RandomizerCore, RandomizerCore.Json, Satchel, SFCore, and finally, Vasi.

**Comment by BubkisLord** [comment]
Hmm.

I see. You aren't missing any dependencies, and I'm not sure what else could be messing with benchwarp.

Just to be sure its Fyrenest, try only using the following mods and see if benchwarp works:
Benchwarp
Fyrenest
ItemChanger
MenuChanger
SFCore
Satchel

If benchwarp is working again, then its another mod thats messing with it.
If benchwarp still doesn't work, then try without any other mods (so only use the Benchwarp mod) and see if it works then.

**Comment by RoninRulez** [comment]
Task Failed Successfully:

It works, but you need to reload the save file to go there. Not the game.
