### ISSUE TITLE
no support for howwowknyight

### ISSUE THREAD

**Issue by Vinter72** [BubkisLord/Fyrenest#5]
hiya ^^ i like playing with the howwowknyight mod on, and noticed that there isn't any support for it, this seems like it isn't such a big problem but what if it were for other mods which change the lore tablets/more.

How about adding a toggle for the changed dialouges in order for players to enjoy the mod if they discover this bug which they can then report and continue enjoying the new charms ^^

or how about adding a toggle which allows the old and new dialouge to show kinda like when you collect too many soul abilities along before visiting the shaman in crossroads during a randomizer, of course this need to be a toggle as it can get anoying ^^ but this has the potential to make the mods more inclusive ^^ although it would be easier with this as a standalone mod...

Sorry! i got derailed... anyways love the mod, just whish for somekinda inclusion ^^ keep up the good work

**Comment by BubkisLord** [comment]
Ok. I'll look into it.
