### ISSUE TITLE
Soul issue

### ISSUE THREAD

**Issue by MythicRage** [BubkisLord/Fyrenest#8]
It only gives me like 4 soul when I hit an enemy, is this intentional?

**Comment by CreeprPlyZ** [comment]
it does the same thing for me, im not sure if its intentional or not

**Comment by BubkisLord** [comment]
> It only gives me like 4 soul when I hit an enemy, is this intentional?

What version of Fyrenest are you using?

**Comment by Skigreen** [comment]
Hi, I'm on the latest release on Scarab and am encountering the same issue.

**Comment by MythicRage** [comment]
It was on version 3.0, the scarab version

**Comment by MythicRage** [comment]
also in the version before 3.0 it gave a lot more than the default soul

**Comment by MythicRage** [comment]
and if you want a picture, this is two hits:
![Screenshot_20230214_035329](https://user-images.githubusercontent.com/119706732/218860702-9b386628-35e0-469b-96b1-e9ac8a06f4d4.png)

**Comment by MythicRage** [comment]
Found Out how to fix this if you are wondering, just extract it, put this in the mod folder, or take out the .dll and put it in the fyrenest folder.
[DoubleSoul.zip](https://github.com/BubkisLord/Fyrenest/files/11180493/DoubleSoul.zip)

**Comment by BubkisLord** [comment]
This has become a part or feature of the mod. If you want, you could use the DoubleSoul.zip file that MythicRage commented.
